### ISSUE TITLE
Url in server.js is region specific for IMF Push Service /notifyAllDevices

### ISSUE THREAD

**Issue by rmey** [ibm-bluemix-mobile-services/bms-samples-hellotodo-advanced#1]
The url in server.js is only working in Bluemix US region in function /notifyAllDevices.
URL should be read from VCAP.
url: "https://mobile.ng.bluemix.net/imfpush/v1/apps/

**Comment by drcariel** [comment]
I've made the update to dynamically use the hosted region.
